# Generated by Django 4.2.4 on 2023-09-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mybackend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spectrum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wavelength", models.FloatField()),
                ("concentration", models.FloatField()),
                ("intensity", models.FloatField()),
            ],
        ),
    ]
